trigger: 
  branches: 
    include:
      - master
      - develop
pool:
   name: 'Default'
variables:
  buildConfiguration: 'Release'
  dotnetVersion: '10.x'
  azureServiceConnection: 'azure-service-connection'
  webAppDev: 'cleanarchdemo-dev'
  webAppProd: 'cleanarchdemo-prod'
  
stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: BuildJob
        displayName: 'Build and Publish'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET $(dotnetVersion)'
            inputs:
              version: $(dotnetVersion)
              packageType: 'sdk'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '**/*.sln'

          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: '**/*.sln'
              arguments: '--configuration $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Publish API'
            inputs:
              command: 'publish'
              projects: 'src/Devops.API/*.csproj'
              arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/api'
              zipAfterPublish: true
          - task: PublishPipelineArtifact@1
            displayName: 'Upload source for testing'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'built-source'
              publishLocation: 'pipeline'

          - task: PublishPipelineArtifact@1
            displayName: 'Upload deployment package'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/api'
              artifactName: 'drop'
              publishLocation: 'pipeline'
  - stage: Test
    displayName: 'Test'
    dependsOn: Build
    jobs:
      - job: TestJob
        displayName: 'Run Tests'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET $(dotnetVersion)'
            inputs:
              version: $(dotnetVersion)
              packageType: 'sdk'
              includePreviewVersions: true

          - task: DownloadPipelineArtifact@2
            displayName: 'Download built source'
            inputs:
              artifactName: 'built-source'
              targetPath: '$(System.DefaultWorkingDirectory)'

          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
              command: 'test'
              projects: 'tests/**/*Tests.csproj'
              arguments: '--configuration $(buildConfiguration) --no-build'
              publishTestResults: true

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish coverage'
            condition: succeededOrFailed()
            inputs:
              summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
              failIfCoverageEmpty: false
              
              
  - stage: MigrateDev
    displayName: 'Migrate Dev Database'
    dependsOn: Test
    condition: |
      and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/develop')
      )
    variables: 
      - group: vg-dev
    jobs:
      - job: MigrateDevJob
        displayName: 'Run Dev Migrations'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET $(dotnetVersion)'
            inputs:
              version: $(dotnetVersion)
              includePreviewVersions: true
              packageType: 'sdk'
          
          - task: DownloadPipelineArtifact@2
            displayName: 'Download built source'
            inputs:
              artifactName: 'built-source'
              targetPath: '$(System.DefaultWorkingDirectory)'
              
          - task: DotNetCoreCLI@2
            displayName: 'RUN dev Migrations'
            inputs: 
              command: 'run'
              projects: 'src/Devops.API/Devops.API.csproj'
              arguments: '--configuration $(buildConfiguration) -- --migrate'
            env:
              connectionStrings__Default: $(ConnectionString)
  
  - stage: MigrateProd
    displayName: 'Migrate to Prod'
    dependsOn: Test
    condition: |
      and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/master')
      )
    variables: 
      - group: vg-prod
    jobs:
      - job: MigrateProdJob
        displayName: 'Run prod migration'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET $(dotnetVersion)'
            inputs: 
              version: $(dotnetVersion)
              packageType: 'sdk'
              includePreviewVersions: true
          
          - task : DownloadPipelineArtifact@2
            displayName: 'Download built source'
            inputs: 
              artifactName: 'built-source'
              targetPath: '$(System.DefaultWorkingDirectory)'
            
          - task: DotNetCoreCLI@2
            displayName: 'Run prod migrations command'
            inputs:
              command: 'run'
              projects: 'src/Devops.API/Devops.API.csproj'
              arguments: '--configuration $(buildConfiguration) -- --migrate'
            env:
              ConnectionStrings__Default: $(ConnectionString)
              
  - stage: DeployDev
    displayName: 'Deploy to Dev'
    dependsOn: MigrateDev
    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      )
    variables:
      - group: vg-dev
    jobs:
      - deployment: DeployDevJob
        displayName: 'Deploy to Dev'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  displayName: 'Install .NET $(dotnetVersion)'
                  inputs:
                    version: $(dotnetVersion)
                    packageType: 'sdk'
                    includePreviewVersions: true

                - task: DownloadPipelineArtifact@2
                  displayName: 'Download deployment package'
                  inputs:
                    artifactName: 'drop'
                    targetPath: '$(System.DefaultWorkingDirectory)/deploy'

                - task: AzureWebApp@1
                  displayName: 'Deploy to Dev App Service'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    appType: 'webApp'
                    appName: '$(webAppDev)'
                    package: '$(System.DefaultWorkingDirectory)/deploy/*.zip'
                    deploymentMethod: 'auto'
                    appSettings: >-
                      -ConnectionStrings__Default "$(ConnectionString)"

  - stage: DeployProd
    displayName: 'Deploy to Prod'
    dependsOn: MigrateProd
    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    variables:
      - group: vg-prod
    jobs:
      - deployment: DeployProdJob
        displayName: 'Deploy to Prod'
        environment: 'Prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  displayName: 'Install .NET $(dotnetVersion)'
                  inputs:
                    version: $(dotnetVersion)
                    packageType: 'sdk'
                    includePreviewVersions: true

                - task: DownloadPipelineArtifact@2
                  displayName: 'Download deployment package'
                  inputs:
                    artifactName: 'drop'
                    targetPath: '$(System.DefaultWorkingDirectory)/deploy'

                - task: AzureWebApp@1
                  displayName: 'Deploy to Prod App Service'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    appType: 'webApp'
                    appName: '$(webAppProd)'
                    package: '$(System.DefaultWorkingDirectory)/deploy/*.zip'
                    deploymentMethod: 'auto'
                    appSettings: >-
                      -ConnectionStrings__Default "$(ConnectionString)"